# Generated by Django 4.2.6 on 2023-10-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='signature_text',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
