# Generated by Django 4.2.6 on 2023-10-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_osoba_options_osoba_data_dodania_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stanowisko',
            old_name='stanowisko',
            new_name='opis',
        ),
    ]
